-- Run this SQL in Supabase SQL Editor.
-- Purpose: persist per-user core data + preferences with RLS protection.

create table if not exists public.user_app_data (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique references auth.users (id) on delete cascade,
  data_version bigint not null default 1,
  content_hash text not null default '',
  device_id text not null default '',
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_user_app_data_user_id on public.user_app_data(user_id);

create or replace function public.set_user_app_data_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_user_app_data_updated_at on public.user_app_data;
create trigger trg_user_app_data_updated_at
before update on public.user_app_data
for each row execute function public.set_user_app_data_updated_at();

alter table public.user_app_data enable row level security;

drop policy if exists "user_app_data_select_own" on public.user_app_data;
create policy "user_app_data_select_own"
on public.user_app_data
for select
using (auth.uid() = user_id);

drop policy if exists "user_app_data_insert_own" on public.user_app_data;
create policy "user_app_data_insert_own"
on public.user_app_data
for insert
with check (auth.uid() = user_id);

drop policy if exists "user_app_data_update_own" on public.user_app_data;
create policy "user_app_data_update_own"
on public.user_app_data
for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "user_app_data_delete_own" on public.user_app_data;
create policy "user_app_data_delete_own"
on public.user_app_data
for delete
using (auth.uid() = user_id);
